### ISSUE TITLE
Remove /src1

### ISSUE THREAD

**Issue by jonnenauha** [realXtend/WebTundra#80]
This folder needs to go. I did not agree on it being there in the first place when dev2 was created, But @antont wanted it there for easy browsing of both new and old files without the need to clone two repos. I understand that but we really need to nuke the folder out, there is always git history or github for nice browsing of the old branch.

**Comment by jonnenauha** [comment]
@cvetan5 You should commit first any pending stuff you have for the release. This step can be done later or even after the release as it wont be included in the prod build anyway.

**Comment by antont** [comment]
i was recalling that opposite that you wanted to commit that dir for some reason and i never wanted it there :)

i just wanted the relevant parts ported over (e.g. the client side xml parsing) and that has been done already. anyhow now the dir is good to go.

**Comment by jonnenauha** [comment]
ok, I have the opposite recollection :D Hehe...

**Comment by cvetan5** [comment]
src1/ removed
